import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from './components/footer'
import Header from './components/header/header'
import Whatsapp from './components/whatsapp'
import "bootstrap-icons/font/bootstrap-icons.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Traga-mas',
  description: 'Generated by SysSosfItegra',
  icons: 'public/faviconChasquis.ico',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {

  

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
        <Whatsapp />
      </body>
    </html>
  )
}
